version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: riauport_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: riauport_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: riauport_db
    restart: always
    environment:
      MYSQL_DATABASE: 3a_riauport
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: riauuser          
      MYSQL_PASSWORD: riaupass      
    ports:
      - "3307:3306"
    volumes:
      - riauport_dbdata:/var/lib/mysql



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: riauport_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PASSWORD: 12345678
    depends_on:
      - db

volumes:
  riauport_dbdata:
